version: '3.8'

services:
  proposals-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: proposals-system
    ports:
      - "3000:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - proposals-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  proposals-network:
    driver: bridge
